---
title: "A step-by-step guide to data processing"
date: "2021-12-31"
output:
  workflowr::wflow_html:
    toc: true
    toc_float:
      collapsed: false
---

## Data Processing

1. The raw datasets were downloaded from the ECI website in XLS format. 
  - [Constituency Data](https://eci.gov.in/files/file/13541-32-constituency-data-summary-report/)
  - [Candidate Data](https://eci.gov.in/files/file/13539-33-constituency-wise-detailed-result/)
  
2. Please refer to the file [code/create_constituency_master.R]() to follow the steps to process data for each constituency.

3. Please refer to the file [code/create-candidate-profile.R]() to follow the steps to process data for each candidate.

4. The Parliament Constituency (PC) GIS file (shape file) was downloaded from the DataMeet website from this [link](http://projects.datameet.org/maps/parliamentary-constituencies/)

5. To plot all data on the map it is important that the geographic entities (States, PC) are refered to be same Name/ID's in the data file and shape file. Please refer to the file [code/geography-matching.R]() to see the list of geographies that had to be updated to ensure common geographies between both files.

6. A master file of constituencies was created by merging the data file and the shape file. Please refer to the file [code/merge-data-gis.R]() to follow the steps to merge both files. 
